// AUTO-GENERATED landing copy (do not edit by hand). en is source; de/fr/es/pt/nl/it from the translation pass.
export const HOME_STRINGS = {
  "en": {
    "nav_how": "How it works",
    "nav_what": "What you get",
    "nav_blog": "Blog",
    "nav_cta": "Get your score",
    "hero_eyebrow": "LinkedIn Intelligence",
    "hero_h1": "Would your profile score <span class=\"gold\">above 50?</span>",
    "hero_lede": "LinkedScore reads your profile, content and positioning, then hands you a scored, personalized plan to fix exactly what's costing you reach.",
    "hero_cta": "Get your score, free →",
    "hero_cta2": "See what's inside",
    "proof_impressions": "Built on a LinkedIn program that hit 3.5M+ impressions",
    "proof_time": "About 5 minutes",
    "proof_nocard": "No card required",
    "dash_label": "Your LinkedScore",
    "dash_tag": "Needs work",
    "dash_outof": "OUT OF 100",
    "dash_note_h": "Example score. Yours is built from your real profile.",
    "dash_note_p": "Your headline and About section are where most of the points are won or lost. The plan shows the exact fixes.",
    "bar_headline": "Headline",
    "bar_about": "About section",
    "bar_experience": "Experience",
    "how_eyebrow": "How it works",
    "how_h2": "Three steps to a scored plan.",
    "how_p": "No generic advice. Everything is built from your real profile and your answers.",
    "step_label": "STEP",
    "step1_h": "Add your profile",
    "step1_p": "Drop your LinkedIn URL and export. We read your headline, About, experience and activity.",
    "step2_h": "Answer a few questions",
    "step2_p": "Tell us your goal and voice. Ten quick questions shape the entire plan around you.",
    "step3_h": "Get your scored report",
    "step3_p": "A 0 to 100 score, graded sections, rewrites, hooks and a 30-day calendar, in about five minutes.",
    "get_eyebrow": "What you get",
    "get_h2": "A full diagnosis, then the fix.",
    "get_p": "Every part is personalized to your role, your goal and what your profile already shows.",
    "f1_h": "Your LinkedScore",
    "f1_p": "One number, 0–100, with a section-by-section breakdown of where you stand.",
    "f2_h": "Revenue at Risk™",
    "f2_p": "The estimated cost of weak positioning, the opportunities your profile is quietly losing.",
    "f2_mini": "€ at risk",
    "f3_h": "Headline & About rewrites",
    "f3_p": "Ready-to-paste rewrites in your own voice, built for search and for humans.",
    "f4_h": "3 post hooks",
    "f4_p": "Three opening hooks written for your voice, each engineered to earn the \"see more\" click.",
    "f5_h": "30-day calendar",
    "f5_p": "A week-by-week roadmap: two strong posts, two engagement weeks, zero filler.",
    "f6_h": "Networking targets",
    "f6_p": "Exactly who to reach, with copy-paste connection and follow-up messages.",
    "founder_h": "Built by Ali Azad",
    "founder_role": "10+ YEARS IN SOCIAL · HUAWEI · QIAGEN",
    "founder_p": "Ali built the executive LinkedIn thought-leadership program at QIAGEN that reached 3.5M+ impressions, and grew his own 10k+ following. Every tactic in LinkedScore is tested on a real profile first — then turned into a plan for yours.",
    "founder_cta": "Work 1:1 with Ali",
    "final_h": "Find out your score.",
    "final_p": "About five minutes. Completely free. No card, no fluff, just your number and the moves to raise it.",
    "footer_tagline": "LinkedScore. LinkedIn growth, scored.",
    "footer_privacy": "Privacy",
    "footer_terms": "Terms",
    "footer_imprint": "Legal",
    "switcher_aria": "Language"
  },
  "de": {
    "nav_how": "So funktioniert's",
    "nav_what": "Das bekommst du",
    "nav_blog": "Blog",
    "nav_cta": "Score holen",
    "hero_eyebrow": "LinkedIn Intelligence",
    "hero_h1": "Würde dein Profil <span class=\"gold\">über 50?</span> punkten",
    "hero_lede": "LinkedScore liest dein Profil, deine Inhalte und deine Positionierung und liefert dir einen bewerteten, persönlichen Plan, der genau das fixt, was dich Reichweite kostet.",
    "hero_cta": "Score holen, gratis →",
    "hero_cta2": "Schau, was drinsteckt",
    "proof_impressions": "Gebaut auf einem LinkedIn-Programm mit über 3.5M+ Impressionen",
    "proof_time": "Rund 5 Minuten",
    "proof_nocard": "Keine Kreditkarte nötig",
    "dash_label": "Dein LinkedScore",
    "dash_tag": "Da geht mehr",
    "dash_outof": "VON 100",
    "dash_note_h": "Beispiel-Score. Deiner entsteht aus deinem echten Profil.",
    "dash_note_p": "In deiner Headline und im Info-Bereich werden die meisten Punkte gewonnen oder verschenkt. Der Plan zeigt dir die genauen Fixes.",
    "bar_headline": "Headline",
    "bar_about": "Info-Bereich",
    "bar_experience": "Berufserfahrung",
    "how_eyebrow": "So funktioniert's",
    "how_h2": "Drei Schritte zum bewerteten Plan.",
    "how_p": "Keine 08/15-Tipps. Alles entsteht aus deinem echten Profil und deinen Antworten.",
    "step_label": "SCHRITT",
    "step1_h": "Profil hinzufügen",
    "step1_p": "Wirf deine LinkedIn-URL und deinen Export rein. Wir lesen Headline, Info, Erfahrung und Aktivität.",
    "step2_h": "Ein paar Fragen beantworten",
    "step2_p": "Sag uns dein Ziel und deinen Ton. Zehn schnelle Fragen formen den ganzen Plan um dich herum.",
    "step3_h": "Bewerteten Report erhalten",
    "step3_p": "Ein Score von 0 bis 100, benotete Abschnitte, Rewrites, Hooks und ein 30-Tage-Kalender, in rund fünf Minuten.",
    "get_eyebrow": "Das bekommst du",
    "get_h2": "Erst die volle Diagnose, dann der Fix.",
    "get_p": "Jeder Teil ist auf deine Rolle, dein Ziel und das zugeschnitten, was dein Profil schon zeigt.",
    "f1_h": "Dein LinkedScore",
    "f1_p": "Eine Zahl, 0–100, mit einer Aufschlüsselung Abschnitt für Abschnitt, wo du stehst.",
    "f2_h": "Gefährdeter Umsatz™",
    "f2_p": "Der geschätzte Preis schwacher Positionierung, die Chancen, die dein Profil still und leise verschenkt.",
    "f2_mini": "€ in Gefahr",
    "f3_h": "Headline- & Info-Rewrites",
    "f3_p": "Fertige Rewrites in deinem eigenen Ton, gemacht für die Suche und für echte Menschen.",
    "f4_h": "3 Post-Hooks",
    "f4_p": "Drei Eröffnungs-Hooks in deinem Ton, jeder darauf getrimmt, den Klick auf \"mehr anzeigen\" zu holen.",
    "f5_h": "30-Tage-Kalender",
    "f5_p": "Eine Woche-für-Woche-Roadmap: zwei starke Posts, zwei Engagement-Wochen, null Füllmaterial.",
    "f6_h": "Networking-Ziele",
    "f6_p": "Genau, wen du ansprechen sollst, mit fertigen Vernetzungs- und Follow-up-Nachrichten zum Kopieren.",
    "founder_h": "Gebaut von Ali Azad",
    "founder_role": "10+ JAHRE IN SOCIAL · HUAWEI · QIAGEN",
    "founder_p": "Ali hat bei QIAGEN das Executive-LinkedIn-Thought-Leadership-Programm aufgebaut, das über 3.5M+ Impressionen erreichte, und seine eigene Followerschaft auf über 10k+ gebracht. Jede Taktik in LinkedScore wird zuerst an einem echten Profil getestet, dann zu einem Plan für deins.",
    "founder_cta": "1:1 mit Ali arbeiten",
    "final_h": "Finde deinen Score heraus.",
    "final_p": "Rund fünf Minuten. Komplett gratis. Keine Karte, kein Blabla, nur deine Zahl und die Moves, um sie zu steigern.",
    "footer_tagline": "LinkedScore. LinkedIn-Wachstum, bewertet.",
    "footer_privacy": "Datenschutz",
    "footer_terms": "AGB",
    "footer_imprint": "Impressum",
    "switcher_aria": "Sprache"
  },
  "fr": {
    "nav_how": "Comment ça marche",
    "nav_what": "Ce que vous obtenez",
    "nav_blog": "Blog",
    "nav_cta": "Obtenir mon score",
    "hero_eyebrow": "L'intelligence LinkedIn",
    "hero_h1": "Votre profil dépasserait-il <span class=\"gold\">la barre des 50 ?</span>",
    "hero_lede": "LinkedScore analyse votre profil, vos contenus et votre positionnement, puis vous livre un plan personnalisé et noté pour corriger précisément ce qui freine votre visibilité.",
    "hero_cta": "Obtenir mon score, gratuit →",
    "hero_cta2": "Voir ce qu'il y a dedans",
    "proof_impressions": "Issu d'un programme LinkedIn qui a dépassé 3.5M+ d'impressions",
    "proof_time": "Environ 5 minutes",
    "proof_nocard": "Sans carte bancaire",
    "dash_label": "Votre LinkedScore",
    "dash_tag": "À améliorer",
    "dash_outof": "SUR 100",
    "dash_note_h": "Score d'exemple. Le vôtre est calculé à partir de votre vrai profil.",
    "dash_note_p": "C'est dans votre titre et votre section Infos que la plupart des points se gagnent ou se perdent. Le plan vous montre exactement quoi corriger.",
    "bar_headline": "Titre",
    "bar_about": "Section Infos",
    "bar_experience": "Expérience",
    "how_eyebrow": "Comment ça marche",
    "how_h2": "Trois étapes vers un plan noté.",
    "how_p": "Aucun conseil générique. Tout est construit à partir de votre vrai profil et de vos réponses.",
    "step_label": "ÉTAPE",
    "step1_h": "Ajoutez votre profil",
    "step1_p": "Collez l'URL de votre profil LinkedIn et son export. Nous lisons votre titre, vos Infos, votre expérience et votre activité.",
    "step2_h": "Répondez à quelques questions",
    "step2_p": "Dites-nous votre objectif et votre ton. Dix questions rapides façonnent tout le plan autour de vous.",
    "step3_h": "Recevez votre rapport noté",
    "step3_p": "Un score de 0 à 100, des sections notées, des réécritures, des accroches et un calendrier sur 30 jours, en environ cinq minutes.",
    "get_eyebrow": "Ce que vous obtenez",
    "get_h2": "Un diagnostic complet, puis la solution.",
    "get_p": "Chaque élément est personnalisé selon votre poste, votre objectif et ce que votre profil montre déjà.",
    "f1_h": "Votre LinkedScore",
    "f1_p": "Un seul chiffre, de 0 à 100, avec une analyse section par section de votre situation.",
    "f2_h": "Revenus en péril™",
    "f2_p": "Le coût estimé d'un positionnement faible : les opportunités que votre profil laisse filer en silence.",
    "f2_mini": "€ en jeu",
    "f3_h": "Réécriture du titre et des Infos",
    "f3_p": "Des réécritures prêtes à coller, dans votre propre ton, pensées pour le référencement et pour les humains.",
    "f4_h": "3 accroches de posts",
    "f4_p": "Trois accroches d'ouverture écrites dans votre ton, chacune conçue pour déclencher le clic sur « voir plus ».",
    "f5_h": "Calendrier sur 30 jours",
    "f5_p": "Une feuille de route semaine par semaine : deux posts forts, deux semaines d'engagement, zéro remplissage.",
    "f6_h": "Cibles de networking",
    "f6_p": "Exactement qui contacter, avec des messages de connexion et de relance prêts à copier-coller.",
    "founder_h": "Créé par Ali Azad",
    "founder_role": "10+ ANS DANS LE SOCIAL · HUAWEI · QIAGEN",
    "founder_p": "Ali a bâti le programme de thought leadership LinkedIn des dirigeants de QIAGEN, qui a atteint 3.5M+ d'impressions, et a fait grandir sa propre audience à 10k+ abonnés. Chaque tactique de LinkedScore est d'abord testée sur un vrai profil, puis transformée en plan pour le vôtre.",
    "founder_cta": "Travailler en 1:1 avec Ali",
    "final_h": "Découvrez votre score.",
    "final_p": "Environ cinq minutes. Entièrement gratuit. Sans carte, sans blabla, juste votre chiffre et les leviers pour le faire grimper.",
    "footer_tagline": "LinkedScore. La croissance LinkedIn, notée.",
    "footer_privacy": "Confidentialité",
    "footer_terms": "Conditions",
    "footer_imprint": "Mentions légales",
    "switcher_aria": "Langue"
  },
  "es": {
    "nav_how": "Cómo funciona",
    "nav_what": "Qué obtienes",
    "nav_blog": "Blog",
    "nav_cta": "Consigue tu puntuación",
    "hero_eyebrow": "Inteligencia para LinkedIn",
    "hero_h1": "¿Tu perfil pasaría de <span class=\"gold\">los 50?</span>",
    "hero_lede": "LinkedScore analiza tu perfil, tu contenido y tu posicionamiento, y te entrega un plan puntuado y a tu medida para arreglar justo lo que te quita alcance.",
    "hero_cta": "Consigue tu puntuación, gratis →",
    "hero_cta2": "Mira qué incluye",
    "proof_impressions": "Creado sobre un programa de LinkedIn que superó los 3.5M+ de impresiones",
    "proof_time": "Unos 5 minutos",
    "proof_nocard": "Sin tarjeta",
    "dash_label": "Tu LinkedScore",
    "dash_tag": "Hay que mejorar",
    "dash_outof": "DE 100",
    "dash_note_h": "Puntuación de ejemplo. La tuya se construye con tu perfil real.",
    "dash_note_p": "Tu titular y tu sección Acerca de son donde se ganan o se pierden casi todos los puntos. El plan te muestra los arreglos exactos.",
    "bar_headline": "Titular",
    "bar_about": "Sección Acerca de",
    "bar_experience": "Experiencia",
    "how_eyebrow": "Cómo funciona",
    "how_h2": "Tres pasos hacia un plan puntuado.",
    "how_p": "Nada de consejos genéricos. Todo se construye a partir de tu perfil real y tus respuestas.",
    "step_label": "PASO",
    "step1_h": "Añade tu perfil",
    "step1_p": "Pega la URL de tu LinkedIn y tu export. Leemos tu titular, tu Acerca de, tu experiencia y tu actividad.",
    "step2_h": "Responde unas preguntas",
    "step2_p": "Cuéntanos tu objetivo y tu estilo. Diez preguntas rápidas moldean todo el plan a tu medida.",
    "step3_h": "Recibe tu informe puntuado",
    "step3_p": "Una puntuación de 0 a 100, secciones calificadas, mejoras, ganchos y un calendario de 30 días, en unos cinco minutos.",
    "get_eyebrow": "Qué obtienes",
    "get_h2": "Un diagnóstico completo y luego la solución.",
    "get_p": "Cada parte está personalizada según tu rol, tu objetivo y lo que tu perfil ya muestra.",
    "f1_h": "Tu LinkedScore",
    "f1_p": "Un solo número, de 0–100, con un desglose sección por sección de dónde estás.",
    "f2_h": "Ingresos en riesgo™",
    "f2_p": "El coste estimado de un posicionamiento débil, las oportunidades que tu perfil pierde sin que te des cuenta.",
    "f2_mini": "€ en riesgo",
    "f3_h": "Mejoras de titular y Acerca de",
    "f3_p": "Versiones listas para pegar en tu propia voz, pensadas para el buscador y para las personas.",
    "f4_h": "3 ganchos para posts",
    "f4_p": "Tres ganchos de apertura escritos en tu estilo, cada uno diseñado para que se gane el clic de \"ver más\".",
    "f5_h": "Calendario de 30 días",
    "f5_p": "Una hoja de ruta semana a semana: dos posts potentes, dos semanas de interacción, cero relleno.",
    "f6_h": "Contactos clave para tu red",
    "f6_p": "A quién contactar exactamente, con mensajes de conexión y seguimiento listos para copiar y pegar.",
    "founder_h": "Creado por Ali Azad",
    "founder_role": "10+ AÑOS EN SOCIAL · HUAWEI · QIAGEN",
    "founder_p": "Ali creó en QIAGEN el programa de liderazgo de opinión para ejecutivos en LinkedIn que alcanzó más de 3.5M+ de impresiones, y hizo crecer su propia comunidad de más de 10k+ seguidores. Cada táctica de LinkedScore se prueba primero en un perfil real, y luego se convierte en un plan para el tuyo.",
    "founder_cta": "Trabaja 1:1 con Ali",
    "final_h": "Descubre tu puntuación.",
    "final_p": "Unos cinco minutos. Totalmente gratis. Sin tarjeta ni relleno, solo tu número y los movimientos para subirlo.",
    "footer_tagline": "LinkedScore. Tu crecimiento en LinkedIn, con puntuación.",
    "footer_privacy": "Privacidad",
    "footer_terms": "Términos",
    "footer_imprint": "Aviso legal",
    "switcher_aria": "Idioma"
  },
  "pt": {
    "nav_how": "Como funciona",
    "nav_what": "O que recebes",
    "nav_blog": "Blog",
    "nav_cta": "Ver a tua pontuação",
    "hero_eyebrow": "Inteligência para o LinkedIn",
    "hero_h1": "O teu perfil ficaria <span class=\"gold\">acima de 50?</span>",
    "hero_lede": "O LinkedScore analisa o teu perfil, conteúdo e posicionamento e entrega-te um plano pontuado e personalizado para corrigir exatamente o que te está a roubar alcance.",
    "hero_cta": "Ver a tua pontuação, grátis →",
    "hero_cta2": "Vê o que está incluído",
    "proof_impressions": "Criado a partir de um programa de LinkedIn que chegou a 3.5M+ impressões",
    "proof_time": "Cerca de 5 minutos",
    "proof_nocard": "Sem cartão necessário",
    "dash_label": "O teu LinkedScore",
    "dash_tag": "Precisa de trabalho",
    "dash_outof": "DE 100",
    "dash_note_h": "Pontuação de exemplo. A tua é construída a partir do teu perfil real.",
    "dash_note_p": "É no teu título e na secção Sobre que se ganham ou perdem quase todos os pontos. O plano mostra-te as correções exatas.",
    "bar_headline": "Título",
    "bar_about": "Secção Sobre",
    "bar_experience": "Experiência",
    "how_eyebrow": "Como funciona",
    "how_h2": "Três passos para um plano pontuado.",
    "how_p": "Nada de conselhos genéricos. Tudo nasce do teu perfil real e das tuas respostas.",
    "step_label": "PASSO",
    "step1_h": "Adiciona o teu perfil",
    "step1_p": "Cola o teu URL do LinkedIn e exporta. Lemos o teu título, Sobre, experiência e atividade.",
    "step2_h": "Responde a algumas perguntas",
    "step2_p": "Diz-nos o teu objetivo e o teu tom. Dez perguntas rápidas moldam todo o plano à tua volta.",
    "step3_h": "Recebe o teu relatório pontuado",
    "step3_p": "Uma pontuação de 0 a 100, secções avaliadas, reescritas, ganchos e um calendário de 30 dias, em cerca de cinco minutos.",
    "get_eyebrow": "O que recebes",
    "get_h2": "Um diagnóstico completo e depois a solução.",
    "get_p": "Cada parte é personalizada para a tua função, o teu objetivo e o que o teu perfil já mostra.",
    "f1_h": "O teu LinkedScore",
    "f1_p": "Um único número, 0–100, com uma análise secção a secção de onde estás.",
    "f2_h": "Receita em Risco™",
    "f2_p": "O custo estimado de um posicionamento fraco, as oportunidades que o teu perfil vai perdendo em silêncio.",
    "f2_mini": "€ em risco",
    "f3_h": "Reescritas do Título e do Sobre",
    "f3_p": "Reescritas prontas a colar, no teu próprio tom, pensadas para a pesquisa e para as pessoas.",
    "f4_h": "3 ganchos para publicações",
    "f4_p": "Três ganchos de abertura escritos no teu tom, cada um pensado para conquistar o clique no \"ver mais\".",
    "f5_h": "Calendário de 30 dias",
    "f5_p": "Um roteiro semana a semana: duas publicações fortes, duas semanas de interação, zero enchimento.",
    "f6_h": "Alvos de networking",
    "f6_p": "Exatamente quem contactar, com mensagens de ligação e de seguimento prontas a colar.",
    "founder_h": "Criado por Ali Azad",
    "founder_role": "10+ ANOS EM SOCIAL · HUAWEI · QIAGEN",
    "founder_p": "O Ali criou na QIAGEN o programa de liderança de pensamento no LinkedIn para executivos que chegou a 3.5M+ impressões, e fez crescer a sua própria audiência para 10k+ seguidores. Cada tática do LinkedScore é primeiro testada num perfil real, e só depois transformada num plano para o teu.",
    "founder_cta": "Trabalha 1:1 com o Ali",
    "final_h": "Descobre a tua pontuação.",
    "final_p": "Cerca de cinco minutos. Totalmente grátis. Sem cartão, sem tretas, só o teu número e as jogadas para o subir.",
    "footer_tagline": "LinkedScore. Crescimento no LinkedIn, com pontuação.",
    "footer_privacy": "Privacidade",
    "footer_terms": "Termos",
    "footer_imprint": "Informações legais",
    "switcher_aria": "Idioma"
  },
  "nl": {
    "nav_how": "Zo werkt het",
    "nav_what": "Wat je krijgt",
    "nav_blog": "Blog",
    "nav_cta": "Ontvang je score",
    "hero_eyebrow": "LinkedIn Intelligence",
    "hero_h1": "Scoort jouw profiel <span class=\"gold\">boven de 50?</span>",
    "hero_lede": "LinkedScore leest je profiel, content en positionering, en geeft je daarna een persoonlijk plan met score om precies te fixen wat je bereik kost.",
    "hero_cta": "Ontvang je score, gratis →",
    "hero_cta2": "Bekijk wat erin zit",
    "proof_impressions": "Gebouwd op een LinkedIn-programma met 3.5M+ impressies",
    "proof_time": "Ongeveer 5 minuten",
    "proof_nocard": "Geen kaart nodig",
    "dash_label": "Jouw LinkedScore",
    "dash_tag": "Kan beter",
    "dash_outof": "VAN 100",
    "dash_note_h": "Voorbeeldscore. De jouwe komt uit je echte profiel.",
    "dash_note_p": "Je kopregel en Info-sectie bepalen de meeste punten, of je ze nu wint of verliest. Het plan laat precies zien wat je moet aanpassen.",
    "bar_headline": "Kopregel",
    "bar_about": "Info-sectie",
    "bar_experience": "Werkervaring",
    "how_eyebrow": "Zo werkt het",
    "how_h2": "In drie stappen naar een plan met score.",
    "how_p": "Geen standaardadvies. Alles is gebouwd op je echte profiel en jouw antwoorden.",
    "step_label": "STAP",
    "step1_h": "Voeg je profiel toe",
    "step1_p": "Plak je LinkedIn-URL en export. Wij lezen je kopregel, Info, werkervaring en activiteit.",
    "step2_h": "Beantwoord een paar vragen",
    "step2_p": "Vertel ons je doel en je toon. Tien snelle vragen vormen het hele plan rond jou.",
    "step3_h": "Ontvang je rapport met score",
    "step3_p": "Een score van 0 tot 100, beoordeelde secties, herschrijvingen, hooks en een kalender van 30 dagen, in ongeveer vijf minuten.",
    "get_eyebrow": "Wat je krijgt",
    "get_h2": "Eerst de volledige diagnose, dan de oplossing.",
    "get_p": "Elk onderdeel is afgestemd op jouw rol, jouw doel en wat je profiel nu al laat zien.",
    "f1_h": "Jouw LinkedScore",
    "f1_p": "Eén getal, 0–100, met een analyse per sectie van waar je staat.",
    "f2_h": "Omzet die je misloopt™",
    "f2_p": "De geschatte kosten van zwakke positionering, de kansen die je profiel stilletjes laat liggen.",
    "f2_mini": "€ op het spel",
    "f3_h": "Herschreven kopregel & Info",
    "f3_p": "Kant-en-klare herschrijvingen in jouw eigen stem, gebouwd voor zoekmachines én voor mensen.",
    "f4_h": "3 post-hooks",
    "f4_p": "Drie openingshooks geschreven in jouw stem, elk ontworpen om die klik op \"meer weergeven\" te verdienen.",
    "f5_h": "Kalender van 30 dagen",
    "f5_p": "Een routekaart week voor week: twee sterke posts, twee weken interactie, nul opvulling.",
    "f6_h": "Netwerkdoelen",
    "f6_p": "Precies wie je moet benaderen, met kant-en-klare connectie- en opvolgberichten.",
    "founder_h": "Gemaakt door Ali Azad",
    "founder_role": "10+ JAAR IN SOCIAL · HUAWEI · QIAGEN",
    "founder_p": "Ali bouwde bij QIAGEN het LinkedIn thought-leadership-programma voor executives dat 3.5M+ impressies haalde, en liet zijn eigen volgersaantal groeien naar 10k+. Elke tactiek in LinkedScore wordt eerst op een echt profiel getest, daarna omgezet in een plan voor het jouwe.",
    "founder_cta": "Werk 1-op-1 met Ali",
    "final_h": "Ontdek jouw score.",
    "final_p": "Ongeveer vijf minuten. Helemaal gratis. Geen kaart, geen gezwets, alleen je getal en de zetten om het te verhogen.",
    "footer_tagline": "LinkedScore. LinkedIn-groei, met een score.",
    "footer_privacy": "Privacy",
    "footer_terms": "Voorwaarden",
    "footer_imprint": "Juridische informatie",
    "switcher_aria": "Taal"
  },
  "it": {
    "nav_how": "Come funziona",
    "nav_what": "Cosa ottieni",
    "nav_blog": "Blog",
    "nav_cta": "Calcola il tuo punteggio",
    "hero_eyebrow": "Intelligenza per LinkedIn",
    "hero_h1": "Il tuo profilo supererebbe <span class=\"gold\">quota 50?</span>",
    "hero_lede": "LinkedScore analizza profilo, contenuti e posizionamento, poi ti consegna un piano personalizzato e con punteggio per sistemare esattamente ciò che ti sta togliendo visibilità.",
    "hero_cta": "Calcola il tuo punteggio, gratis →",
    "hero_cta2": "Guarda cosa c'è dentro",
    "proof_impressions": "Nato da un programma LinkedIn che ha superato 3.5M+ di impression",
    "proof_time": "Circa 5 minuti",
    "proof_nocard": "Nessuna carta richiesta",
    "dash_label": "Il tuo LinkedScore",
    "dash_tag": "Da migliorare",
    "dash_outof": "SU 100",
    "dash_note_h": "Punteggio di esempio. Il tuo nasce dal tuo profilo reale.",
    "dash_note_p": "È nel titolo e nella sezione Informazioni che si vince o si perde la maggior parte dei punti. Il piano ti mostra le correzioni esatte.",
    "bar_headline": "Titolo",
    "bar_about": "Sezione Informazioni",
    "bar_experience": "Esperienza",
    "how_eyebrow": "Come funziona",
    "how_h2": "Tre passi verso un piano con punteggio.",
    "how_p": "Niente consigli generici. Tutto nasce dal tuo profilo reale e dalle tue risposte.",
    "step_label": "PASSO",
    "step1_h": "Aggiungi il tuo profilo",
    "step1_p": "Incolla l'URL di LinkedIn e l'esportazione. Analizziamo titolo, Informazioni, esperienza e attività.",
    "step2_h": "Rispondi a qualche domanda",
    "step2_p": "Dicci il tuo obiettivo e il tuo tono. Dieci domande veloci modellano l'intero piano su di te.",
    "step3_h": "Ricevi il tuo report con punteggio",
    "step3_p": "Un punteggio da 0 a 100, sezioni valutate, riscritture, hook e un calendario di 30 giorni, in circa cinque minuti.",
    "get_eyebrow": "Cosa ottieni",
    "get_h2": "Prima la diagnosi completa, poi la cura.",
    "get_p": "Ogni parte è personalizzata sul tuo ruolo, sul tuo obiettivo e su ciò che il tuo profilo già mostra.",
    "f1_h": "Il tuo LinkedScore",
    "f1_p": "Un solo numero, 0–100, con un'analisi sezione per sezione di dove ti trovi.",
    "f2_h": "Fatturato a Rischio™",
    "f2_p": "Il costo stimato di un posizionamento debole, le opportunità che il tuo profilo sta perdendo in silenzio.",
    "f2_mini": "€ a rischio",
    "f3_h": "Titolo e Informazioni riscritti",
    "f3_p": "Riscritture pronte da incollare, nel tuo tono, pensate per la ricerca e per le persone.",
    "f4_h": "3 hook per i post",
    "f4_p": "Tre hook di apertura scritti nel tuo tono, ognuno progettato per guadagnare il clic su \"mostra altro\".",
    "f5_h": "Calendario di 30 giorni",
    "f5_p": "Una roadmap settimana per settimana: due post forti, due settimane di engagement, zero riempitivi.",
    "f6_h": "Contatti da coltivare",
    "f6_p": "Esattamente chi contattare, con messaggi di collegamento e follow-up pronti da incollare.",
    "founder_h": "Creato da Ali Azad",
    "founder_role": "10+ ANNI NEI SOCIAL · HUAWEI · QIAGEN",
    "founder_p": "Ali ha costruito in QIAGEN il programma di thought leadership su LinkedIn per i dirigenti, arrivando a 3.5M+ di impression, e ha fatto crescere il proprio seguito a 10k+. Ogni tattica di LinkedScore viene prima testata su un profilo reale, poi trasformata in un piano per il tuo.",
    "founder_cta": "Lavora 1:1 con Ali",
    "final_h": "Scopri il tuo punteggio.",
    "final_p": "Circa cinque minuti. Completamente gratis. Niente carta, niente fronzoli, solo il tuo numero e le mosse per alzarlo.",
    "footer_tagline": "LinkedScore. La crescita su LinkedIn, con un punteggio.",
    "footer_privacy": "Privacy",
    "footer_terms": "Termini",
    "footer_imprint": "Note legali",
    "switcher_aria": "Lingua"
  }
};

export const HOME_META = {
  "en": {
    "title": "Linkedscore — LinkedIn Growth Plan",
    "description": "Get your free LinkedIn Score and a personalized AI growth plan: profile rewrites, post hooks and a 30-day roadmap built for your goal."
  },
  "de": {
    "title": "Linkedscore — Dein LinkedIn-Score & KI-Plan",
    "description": "Hol dir deinen kostenlosen LinkedIn-Score und einen persönlichen KI-Wachstumsplan: Profil-Rewrites, Post-Hooks und eine 30-Tage-Roadmap für dein Ziel."
  },
  "fr": {
    "title": "Linkedscore — Votre score et plan LinkedIn par IA",
    "description": "Obtenez votre score LinkedIn gratuit et un plan de croissance personnalisé par IA : profil réécrit, accroches de posts et feuille de route sur 30 jours."
  },
  "es": {
    "title": "Linkedscore — Plan de crecimiento en LinkedIn",
    "description": "Consigue gratis tu puntuación de LinkedIn y un plan de crecimiento con IA: mejoras de perfil, ganchos para posts y una hoja de ruta de 30 días."
  },
  "pt": {
    "title": "Linkedscore — Plano de Crescimento no LinkedIn",
    "description": "Descobre a tua pontuação do LinkedIn grátis e um plano de crescimento com IA: reescritas do perfil do LinkedIn, ganchos e roteiro de 30 dias."
  },
  "nl": {
    "title": "Linkedscore — Jouw LinkedIn-groeiplan met AI",
    "description": "Ontvang gratis je LinkedIn-score en een persoonlijk AI-groeiplan: herschreven profiel, sterke post-hooks en een routekaart van 30 dagen voor jouw doel."
  },
  "it": {
    "title": "Linkedscore — Piano di crescita su LinkedIn con IA",
    "description": "Scopri il tuo punteggio LinkedIn gratis e un piano di crescita personalizzato con IA: profilo riscritto, hook per i post e una roadmap di 30 giorni su misura."
  }
};
