// AUTO-GENERATED landing copy (do not edit by hand). en is source; de/fr/es/pt/nl/it from the translation pass.
export const HOME_STRINGS = {
  "en": {
    "nav_how": "How it works",
    "nav_what": "What you get",
    "nav_writer": "Post Writer",
    "nav_blog": "Blog",
    "nav_about": "About",
    "nav_faq": "FAQ",
    "nav_cta": "Your score",
    "hero_eyebrow": "LinkedIn Intelligence",
    "hero_h1": "<span class=\"gold\">Crack the LinkedIn algorithm.</span> Get seen.",
    "hero_lede": "We read your real profile and posts, decode what the feed rewards and hand you the plan to lead your field.",
    "edge1": "Reads your real <b>posts</b>, not just your profile",
    "edge2": "<b>Two scores</b>, for your profile and your thought leadership",
    "edge3": "A plan to make you a <b>voice</b>, not just a number",
    "edge4": "A <b>Post Writer</b> that drafts your next posts in your voice",
    "hero_cta": "Get your score, free →",
    "hero_cta2": "See what's inside",
    "proof_impressions": "<b>3.5M+ impressions</b> behind the method",
    "proof_time": "About 10 minutes",
    "proof_nocard": "No card required",
    "dash_label": "Your LinkedScore",
    "dash_tag": "Needs work",
    "dash_outof": "OUT OF 100",
    "dash_note_h": "Example score. Yours is built from your real profile.",
    "dash_note_p": "Your headline and About section are where most of the points are won or lost. The plan shows the exact fixes.",
    "bar_headline": "Headline",
    "bar_about": "About section",
    "bar_experience": "Experience",
    "how_eyebrow": "How it works",
    "how_h2": "Three steps to a recognized voice.",
    "how_p": "No generic advice. We read your real profile and your actual posts, then build the plan around you.",
    "step_label": "STEP",
    "step1_h": "Show your real work",
    "step1_p": "Add your LinkedIn profile and screenshots of your last 3 posts so we read what you actually publish, not just your headline.",
    "step2_h": "Answer a few questions",
    "step2_p": "Tell us your goal and your voice in about ten quick questions that shape the entire plan around you.",
    "step3_h": "Get two scores",
    "step3_p": "Your LinkedIn Score and your Thought Leader Score, so you see exactly where your profile and your content stand.",
    "get_eyebrow": "What you get",
    "get_h2": "Most tools stop at a score. We don't.",
    "get_p": "Every part is personalized to your role, your goal and what your profile already shows.",
    "f1_h": "Your two scores",
    "f1_p": "A LinkedIn Score for your profile and a Thought Leader Score for your posts, each 0 to 100 with a section-by-section breakdown.",
    "f2_h": "Revenue at Risk™",
    "f2_p": "The estimated cost of weak positioning, the opportunities your profile is quietly losing.",
    "f2_mini": "$ at risk",
    "f3_h": "Headline & About rewrites",
    "f3_p": "Ready-to-paste rewrites in your own voice, built for search and for humans.",
    "f4_h": "3 post hooks",
    "f4_p": "Three opening hooks written for your voice, each engineered to earn the \"see more\" click.",
    "f5_h": "30-day calendar",
    "f5_p": "A week-by-week roadmap: two strong posts, two engagement weeks, zero filler.",
    "f6_h": "Networking targets",
    "f6_p": "Exactly who to reach, with copy-paste connection and follow-up messages.",
    "writer_eyebrow": "After the report",
    "writer_h2": "The report is day one. Then it writes with you.",
    "writer_p": "Create a free account and the plan stops being a document. Your voice is saved, your next post is drafted and your progress is measured.",
    "w1_h": "Post Writer",
    "w1_p": "Paste a rough draft or a half-formed idea. You get back a LinkedIn-ready post in your voice, hook first, built on the same rules as your plan. Tell it what to change and it refines.",
    "w2_h": "Your voice, saved",
    "w2_p": "Your report already learned how you write. The writer reuses that voice for every new post, so it sounds like you, not like a template. Nothing to re-upload.",
    "w3_h": "A score you can retest",
    "w3_p": "Every report is saved to your dashboard. Apply the fixes, run it again and the score moves with the improvement, because it measures your profile instead of guessing.",
    "founder_h": "Built by Ali Azad",
    "founder_role": "10+ YEARS IN SOCIAL · HUAWEI · QIAGEN",
    "founder_p": "Ali builds and runs an executive LinkedIn thought-leadership program for a living. His QIAGEN program reached 3.5M+ impressions and his own following passed 10k+. Turning profiles into recognized voices is his day job, so every tactic in LinkedScore is tested on real executive profiles first, then turned into a plan for yours.",
    "founder_cta": "Work 1:1 with Ali",
    "final_h": "See how you're positioned.",
    "final_p": "About ten minutes. Completely free. No card, no fluff, just your two scores, your plan and a Post Writer in your voice.",
    "footer_tagline": "LinkedScore. Become a voice, not just a number.",
    "footer_privacy": "Privacy",
    "footer_terms": "Terms",
    "footer_imprint": "Legal",
    "footer_cookies": "Cookies",
    "switcher_aria": "Language"
  },
  "de": {
    "nav_how": "So funktioniert's",
    "nav_what": "Das bekommst du",
    "nav_blog": "Blog",
    "nav_about": "Über uns",
    "nav_cta": "Score holen",
    "hero_eyebrow": "LinkedIn Intelligence",
    "hero_h1": "<span class=\"gold\">Knack den LinkedIn-Algorithmus.</span> Werd sichtbar.",
    "hero_lede": "LinkedScore liest dein Profil, deine Inhalte und deine Positionierung und liefert dir einen bewerteten, persönlichen Plan, der genau das fixt, was dich Reichweite kostet.",
    "edge1": "Liest deine echten <b>Posts</b>, nicht nur dein Profil",
    "edge2": "<b>Zwei Scores</b>, für dein Profil und deine Thought Leadership",
    "edge3": "Ein Plan, der dich zur <b>Stimme</b> macht, nicht zur Nummer",
    "edge4": "Ein <b>Post Writer</b>, der deine nächsten Posts in deinem Ton schreibt",
    "hero_cta": "Score holen, gratis →",
    "hero_cta2": "Schau, was drinsteckt",
    "proof_impressions": "Hinter der Methode stehen <b>über 3.5M+ Impressionen</b>",
    "proof_time": "Rund 10 Minuten",
    "proof_nocard": "Keine Kreditkarte nötig",
    "dash_label": "Dein LinkedScore",
    "dash_tag": "Da geht mehr",
    "dash_outof": "VON 100",
    "dash_note_h": "Beispiel-Score. Deiner entsteht aus deinem echten Profil.",
    "dash_note_p": "In deiner Headline und im Info-Bereich werden die meisten Punkte gewonnen oder verschenkt. Der Plan zeigt dir die genauen Fixes.",
    "bar_headline": "Headline",
    "bar_about": "Info-Bereich",
    "bar_experience": "Berufserfahrung",
    "how_eyebrow": "So funktioniert's",
    "how_h2": "Drei Schritte zur anerkannten Stimme.",
    "how_p": "Keine 08/15-Tipps. Wir lesen dein echtes Profil und deine tatsächlichen Posts und bauen den Plan um dich herum.",
    "step_label": "SCHRITT",
    "step1_h": "Zeig deine echte Arbeit",
    "step1_p": "Füg dein LinkedIn-Profil und Screenshots deiner letzten 3 Posts hinzu, damit wir lesen, was du wirklich veröffentlichst, nicht nur deine Headline.",
    "step2_h": "Ein paar Fragen beantworten",
    "step2_p": "Sag uns dein Ziel und deinen Ton in rund zehn schnellen Fragen, die den ganzen Plan um dich herum formen.",
    "step3_h": "Zwei Scores erhalten",
    "step3_p": "Dein LinkedIn Score und dein Thought Leader Score, damit du genau siehst, wo dein Profil und deine Inhalte stehen.",
    "get_eyebrow": "Das bekommst du",
    "get_h2": "Die meisten Tools hören beim Score auf. Wir nicht.",
    "get_p": "Jeder Teil ist auf deine Rolle, dein Ziel und das zugeschnitten, was dein Profil schon zeigt.",
    "f1_h": "Deine zwei Scores",
    "f1_p": "Ein LinkedIn Score für dein Profil und ein Thought Leader Score für deine Posts, jeweils 0 bis 100 mit einer Aufschlüsselung Abschnitt für Abschnitt.",
    "f2_h": "Gefährdeter Umsatz™",
    "f2_p": "Der geschätzte Preis schwacher Positionierung, die Chancen, die dein Profil still und leise verschenkt.",
    "f2_mini": "€ in Gefahr",
    "f3_h": "Headline- & Info-Rewrites",
    "f3_p": "Fertige Rewrites in deinem eigenen Ton, gemacht für die Suche und für echte Menschen.",
    "f4_h": "3 Post-Hooks",
    "f4_p": "Drei Eröffnungs-Hooks in deinem Ton, jeder darauf getrimmt, den Klick auf \"mehr anzeigen\" zu holen.",
    "f5_h": "30-Tage-Kalender",
    "f5_p": "Eine Woche-für-Woche-Roadmap: zwei starke Posts, zwei Engagement-Wochen, null Füllmaterial.",
    "f6_h": "Networking-Ziele",
    "f6_p": "Genau, wen du ansprechen sollst, mit fertigen Vernetzungs- und Follow-up-Nachrichten zum Kopieren.",
    "writer_eyebrow": "Nach dem Report",
    "writer_h2": "Der Report ist Tag eins. Danach schreibt er mit dir.",
    "writer_p": "Erstell dir ein kostenloses Konto und der Plan hört auf, nur ein Dokument zu sein. Dein Ton wird gespeichert, dein nächster Post entworfen und dein Fortschritt gemessen.",
    "w1_h": "Post Writer",
    "w1_p": "Füg einen groben Entwurf oder eine halbfertige Idee ein. Du bekommst einen fertigen LinkedIn-Post in deinem Ton zurück, Hook zuerst, gebaut nach denselben Regeln wie dein Plan. Sag ihm, was du ändern willst, und er bessert nach.",
    "w2_h": "Dein Ton, gespeichert",
    "w2_p": "Dein Report hat schon gelernt, wie du schreibst. Der Post Writer nutzt diesen Ton für jeden neuen Post, damit er nach dir klingt, nicht nach einer Vorlage. Nichts muss neu hochgeladen werden.",
    "w3_h": "Ein Score, den du neu messen kannst",
    "w3_p": "Jeder Report wird in deinem Dashboard gespeichert. Setz die Fixes um, lass ihn nochmal laufen und der Score bewegt sich mit, weil er dein Profil misst, statt zu raten.",
    "founder_h": "Gebaut von Ali Azad",
    "founder_role": "10+ JAHRE IN SOCIAL · HUAWEI · QIAGEN",
    "founder_p": "Ali baut und leitet hauptberuflich ein Executive-LinkedIn-Thought-Leadership-Programm. Sein QIAGEN-Programm erreichte über 3.5M+ Impressionen und seine eigene Followerschaft knackte die 10k+. Profile in anerkannte Stimmen zu verwandeln ist sein Tagesgeschäft, deshalb wird jede Taktik in LinkedScore zuerst an echten Executive-Profilen getestet und dann zu einem Plan für deins.",
    "founder_cta": "1:1 mit Ali arbeiten",
    "final_h": "Sieh, wie du positioniert bist.",
    "final_p": "Rund zehn Minuten. Komplett gratis. Keine Karte, kein Blabla, nur deine zwei Scores, dein Plan und ein Post Writer in deinem Ton.",
    "footer_tagline": "LinkedScore. Werd eine Stimme, nicht nur eine Nummer.",
    "footer_privacy": "Datenschutz",
    "footer_terms": "AGB",
    "footer_imprint": "Impressum",
    "footer_cookies": "Cookies",
    "switcher_aria": "Sprache"
  },
  "fr": {
    "nav_how": "Comment ça marche",
    "nav_what": "Ce que vous obtenez",
    "nav_blog": "Blog",
    "nav_about": "À propos",
    "nav_cta": "Mon score",
    "hero_eyebrow": "L'intelligence LinkedIn",
    "hero_h1": "<span class=\"gold\">Percez l'algorithme LinkedIn.</span> Faites-vous voir.",
    "hero_lede": "LinkedScore analyse votre profil, vos contenus et votre positionnement, puis vous livre un plan personnalisé et noté pour corriger précisément ce qui freine votre visibilité.",
    "edge1": "Analyse vos vraies <b>publications</b>, pas seulement votre profil",
    "edge2": "<b>Deux scores</b>, pour votre profil et votre leadership d'opinion",
    "edge3": "Un plan pour faire de vous une <b>voix</b>, pas un simple chiffre",
    "edge4": "Un <b>Post Writer</b> qui rédige vos prochains posts dans votre ton",
    "hero_cta": "Obtenir mon score, gratuit →",
    "hero_cta2": "Voir ce qu'il y a dedans",
    "proof_impressions": "Une méthode forgée par <b>3.5M+ d'impressions</b>",
    "proof_time": "Environ 10 minutes",
    "proof_nocard": "Sans carte bancaire",
    "dash_label": "Votre LinkedScore",
    "dash_tag": "À améliorer",
    "dash_outof": "SUR 100",
    "dash_note_h": "Score d'exemple. Le vôtre est calculé à partir de votre vrai profil.",
    "dash_note_p": "C'est dans votre titre et votre section Infos que la plupart des points se gagnent ou se perdent. Le plan vous montre exactement quoi corriger.",
    "bar_headline": "Titre",
    "bar_about": "Section Infos",
    "bar_experience": "Expérience",
    "how_eyebrow": "Comment ça marche",
    "how_h2": "Trois étapes vers une voix reconnue.",
    "how_p": "Aucun conseil générique. Nous lisons votre vrai profil et vos vraies publications, puis nous construisons le plan autour de vous.",
    "step_label": "ÉTAPE",
    "step1_h": "Montrez votre vrai travail",
    "step1_p": "Ajoutez votre profil LinkedIn et des captures de vos 3 dernières publications, pour que nous lisions ce que vous publiez vraiment, pas seulement votre titre.",
    "step2_h": "Répondez à quelques questions",
    "step2_p": "Dites-nous votre objectif et votre voix en une dizaine de questions rapides qui façonnent tout le plan autour de vous.",
    "step3_h": "Recevez deux scores",
    "step3_p": "Votre LinkedIn Score et votre Thought Leader Score, pour voir exactement où en sont votre profil et votre contenu.",
    "get_eyebrow": "Ce que vous obtenez",
    "get_h2": "La plupart des outils s'arrêtent à un score. Pas nous.",
    "get_p": "Chaque élément est personnalisé selon votre poste, votre objectif et ce que votre profil montre déjà.",
    "f1_h": "Vos deux scores",
    "f1_p": "Un LinkedIn Score pour votre profil et un Thought Leader Score pour vos publications, chacun de 0 à 100 avec une analyse section par section.",
    "f2_h": "Revenus en péril™",
    "f2_p": "Le coût estimé d'un positionnement faible : les opportunités que votre profil laisse filer en silence.",
    "f2_mini": "€ en jeu",
    "f3_h": "Réécriture du titre et des Infos",
    "f3_p": "Des réécritures prêtes à coller, dans votre propre ton, pensées pour le référencement et pour les humains.",
    "f4_h": "3 accroches de posts",
    "f4_p": "Trois accroches d'ouverture écrites dans votre ton, chacune conçue pour déclencher le clic sur « voir plus ».",
    "f5_h": "Calendrier sur 30 jours",
    "f5_p": "Une feuille de route semaine par semaine : deux posts forts, deux semaines d'engagement, zéro remplissage.",
    "f6_h": "Cibles de networking",
    "f6_p": "Exactement qui contacter, avec des messages de connexion et de relance prêts à copier-coller.",
    "writer_eyebrow": "Après le rapport",
    "writer_h2": "Le rapport, c'est le jour un. Ensuite, il écrit avec vous.",
    "writer_p": "Créez un compte gratuit et le plan cesse d'être un simple document. Votre ton est enregistré, votre prochain post est rédigé et vos progrès sont mesurés.",
    "w1_h": "Post Writer",
    "w1_p": "Collez un brouillon ou une idée à peine ébauchée. Vous récupérez un post prêt pour LinkedIn dans votre ton, accroche en tête, construit sur les mêmes règles que votre plan. Dites-lui quoi changer et il affine.",
    "w2_h": "Votre ton, enregistré",
    "w2_p": "Votre rapport a déjà appris votre façon d'écrire. Le Post Writer réutilise ce ton pour chaque nouveau post : on dirait vous, pas un modèle. Rien à renvoyer.",
    "w3_h": "Un score que vous pouvez retester",
    "w3_p": "Chaque rapport est enregistré dans votre tableau de bord. Appliquez les corrections, relancez l'analyse et le score bouge avec vos progrès, parce qu'il mesure votre profil au lieu de deviner.",
    "founder_h": "Créé par Ali Azad",
    "founder_role": "10+ ANS DANS LE SOCIAL · HUAWEI · QIAGEN",
    "founder_p": "Ali bâtit et pilote au quotidien un programme de thought leadership LinkedIn pour dirigeants. Son programme chez QIAGEN a atteint 3.5M+ d'impressions et sa propre audience a dépassé 10k+ abonnés. Transformer des profils en voix reconnues est son métier, alors chaque tactique de LinkedScore est d'abord testée sur de vrais profils de dirigeants, puis transformée en plan pour le vôtre.",
    "founder_cta": "Travailler en 1:1 avec Ali",
    "final_h": "Voyez comment vous êtes positionné.",
    "final_p": "Environ dix minutes. Entièrement gratuit. Sans carte, sans blabla, juste vos deux scores, votre plan et un Post Writer dans votre ton.",
    "footer_tagline": "LinkedScore. Devenez une voix, pas un simple chiffre.",
    "footer_privacy": "Confidentialité",
    "footer_terms": "Conditions",
    "footer_imprint": "Mentions légales",
    "footer_cookies": "Cookies",
    "switcher_aria": "Langue"
  },
  "es": {
    "nav_how": "Cómo funciona",
    "nav_what": "Qué obtienes",
    "nav_blog": "Blog",
    "nav_about": "Nosotros",
    "nav_cta": "Tu score",
    "hero_eyebrow": "Inteligencia para LinkedIn",
    "hero_h1": "<span class=\"gold\">Descifra el algoritmo de LinkedIn.</span> Hazte ver.",
    "hero_lede": "LinkedScore analiza tu perfil, tu contenido y tu posicionamiento, y te entrega un plan puntuado y a tu medida para arreglar justo lo que te quita alcance.",
    "edge1": "Lee tus <b>publicaciones</b> reales, no solo tu perfil",
    "edge2": "<b>Dos puntuaciones</b>, para tu perfil y tu liderazgo de opinión",
    "edge3": "Un plan para convertirte en una <b>voz</b>, no solo en un número",
    "edge4": "Un <b>Post Writer</b> que redacta tus próximas publicaciones en tu voz",
    "hero_cta": "Consigue tu puntuación, gratis →",
    "hero_cta2": "Mira qué incluye",
    "proof_impressions": "<b>Más de 3.5M+ de impresiones</b> detrás del método",
    "proof_time": "Unos 10 minutos",
    "proof_nocard": "Sin tarjeta",
    "dash_label": "Tu LinkedScore",
    "dash_tag": "Hay que mejorar",
    "dash_outof": "DE 100",
    "dash_note_h": "Puntuación de ejemplo. La tuya se construye con tu perfil real.",
    "dash_note_p": "Tu titular y tu sección Acerca de son donde se ganan o se pierden casi todos los puntos. El plan te muestra los arreglos exactos.",
    "bar_headline": "Titular",
    "bar_about": "Sección Acerca de",
    "bar_experience": "Experiencia",
    "how_eyebrow": "Cómo funciona",
    "how_h2": "Tres pasos hacia una voz reconocida.",
    "how_p": "Nada de consejos genéricos. Leemos tu perfil real y tus publicaciones reales, y luego construimos el plan a tu medida.",
    "step_label": "PASO",
    "step1_h": "Muestra tu trabajo real",
    "step1_p": "Añade tu perfil de LinkedIn y capturas de tus últimas 3 publicaciones para que leamos lo que de verdad publicas, no solo tu titular.",
    "step2_h": "Responde unas preguntas",
    "step2_p": "Cuéntanos tu objetivo y tu estilo en unas diez preguntas rápidas que moldean todo el plan a tu medida.",
    "step3_h": "Recibe dos puntuaciones",
    "step3_p": "Tu LinkedIn Score y tu Thought Leader Score, para que veas exactamente dónde están tu perfil y tu contenido.",
    "get_eyebrow": "Qué obtienes",
    "get_h2": "La mayoría de las herramientas se quedan en una puntuación. Nosotros no.",
    "get_p": "Cada parte está personalizada según tu rol, tu objetivo y lo que tu perfil ya muestra.",
    "f1_h": "Tus dos puntuaciones",
    "f1_p": "Un LinkedIn Score para tu perfil y un Thought Leader Score para tus publicaciones, cada uno de 0 a 100 con un desglose sección por sección.",
    "f2_h": "Ingresos en riesgo™",
    "f2_p": "El coste estimado de un posicionamiento débil, las oportunidades que tu perfil pierde sin que te des cuenta.",
    "f2_mini": "€ en riesgo",
    "f3_h": "Mejoras de titular y Acerca de",
    "f3_p": "Versiones listas para pegar en tu propia voz, pensadas para el buscador y para las personas.",
    "f4_h": "3 ganchos para posts",
    "f4_p": "Tres ganchos de apertura escritos en tu estilo, cada uno diseñado para que se gane el clic de \"ver más\".",
    "f5_h": "Calendario de 30 días",
    "f5_p": "Una hoja de ruta semana a semana: dos posts potentes, dos semanas de interacción, cero relleno.",
    "f6_h": "Contactos clave para tu red",
    "f6_p": "A quién contactar exactamente, con mensajes de conexión y seguimiento listos para copiar y pegar.",
    "writer_eyebrow": "Después del informe",
    "writer_h2": "El informe es el día uno. Luego escribe contigo.",
    "writer_p": "Crea una cuenta gratis y el plan deja de ser un documento. Tu voz se guarda, tu próximo post se redacta y tu progreso se mide.",
    "w1_h": "Post Writer",
    "w1_p": "Pega un borrador sin pulir o una idea a medias. Recibes un post listo para LinkedIn en tu voz, con el gancho por delante, construido con las mismas reglas que tu plan. Dile qué cambiar y lo refina.",
    "w2_h": "Tu voz, guardada",
    "w2_p": "Tu informe ya ha aprendido cómo escribes. El Post Writer reutiliza esa voz en cada post nuevo, así que suena a ti, no a una plantilla. Sin volver a subir nada.",
    "w3_h": "Una puntuación que puedes volver a medir",
    "w3_p": "Cada informe se guarda en tu panel. Aplica los arreglos, repítelo y la puntuación se mueve con tu mejora, porque mide tu perfil en lugar de adivinar.",
    "founder_h": "Creado por Ali Azad",
    "founder_role": "10+ AÑOS EN SOCIAL · HUAWEI · QIAGEN",
    "founder_p": "Ali crea y dirige un programa de liderazgo de opinión en LinkedIn para ejecutivos como profesión. Su programa en QIAGEN alcanzó más de 3.5M+ de impresiones y su propia comunidad superó los 10k+ seguidores. Convertir perfiles en voces reconocidas es su trabajo diario, así que cada táctica de LinkedScore se prueba primero en perfiles ejecutivos reales, y luego se convierte en un plan para el tuyo.",
    "founder_cta": "Trabaja 1:1 con Ali",
    "final_h": "Descubre cómo estás posicionado.",
    "final_p": "Unos diez minutos. Totalmente gratis. Sin tarjeta ni relleno, solo tus dos puntuaciones, tu plan y un Post Writer en tu voz.",
    "footer_tagline": "LinkedScore. Conviértete en una voz, no solo en un número.",
    "footer_privacy": "Privacidad",
    "footer_terms": "Términos",
    "footer_imprint": "Aviso legal",
    "footer_cookies": "Cookies",
    "switcher_aria": "Idioma"
  },
  "pt": {
    "nav_how": "Como funciona",
    "nav_what": "O que recebes",
    "nav_blog": "Blog",
    "nav_about": "Sobre",
    "nav_cta": "O teu score",
    "hero_eyebrow": "Inteligência para o LinkedIn",
    "hero_h1": "<span class=\"gold\">Decifra o algoritmo do LinkedIn.</span> Faz-te notar.",
    "hero_lede": "O LinkedScore analisa o teu perfil, conteúdo e posicionamento e entrega-te um plano pontuado e personalizado para corrigir exatamente o que te está a roubar alcance.",
    "edge1": "Lê os teus <b>posts</b> reais, não só o teu perfil",
    "edge2": "<b>Duas pontuações</b>, para o teu perfil e para a tua liderança de pensamento",
    "edge3": "Um plano para te tornar uma <b>voz</b>, não apenas um número",
    "edge4": "Um <b>Post Writer</b> que escreve os teus próximos posts no teu tom",
    "hero_cta": "Ver a tua pontuação, grátis →",
    "hero_cta2": "Vê o que está incluído",
    "proof_impressions": "<b>Mais de 3.5M+ impressões</b> por trás do método",
    "proof_time": "Cerca de 10 minutos",
    "proof_nocard": "Sem cartão necessário",
    "dash_label": "O teu LinkedScore",
    "dash_tag": "Precisa de trabalho",
    "dash_outof": "DE 100",
    "dash_note_h": "Pontuação de exemplo. A tua é construída a partir do teu perfil real.",
    "dash_note_p": "É no teu título e na secção Sobre que se ganham ou perdem quase todos os pontos. O plano mostra-te as correções exatas.",
    "bar_headline": "Título",
    "bar_about": "Secção Sobre",
    "bar_experience": "Experiência",
    "how_eyebrow": "Como funciona",
    "how_h2": "Três passos para uma voz reconhecida.",
    "how_p": "Nada de conselhos genéricos. Lemos o teu perfil real e os teus posts reais, e depois construímos o plano à tua volta.",
    "step_label": "PASSO",
    "step1_h": "Mostra o teu trabalho real",
    "step1_p": "Adiciona o teu perfil do LinkedIn e capturas de ecrã dos teus últimos 3 posts para que leiamos o que publicas de verdade, não só o teu título.",
    "step2_h": "Responde a algumas perguntas",
    "step2_p": "Diz-nos o teu objetivo e o teu tom em cerca de dez perguntas rápidas que moldam todo o plano à tua volta.",
    "step3_h": "Recebe duas pontuações",
    "step3_p": "O teu LinkedIn Score e o teu Thought Leader Score, para veres exatamente onde estão o teu perfil e o teu conteúdo.",
    "get_eyebrow": "O que recebes",
    "get_h2": "A maioria das ferramentas para numa pontuação. Nós não.",
    "get_p": "Cada parte é personalizada para a tua função, o teu objetivo e o que o teu perfil já mostra.",
    "f1_h": "As tuas duas pontuações",
    "f1_p": "Um LinkedIn Score para o teu perfil e um Thought Leader Score para os teus posts, cada um de 0 a 100, com uma análise secção a secção.",
    "f2_h": "Receita em Risco™",
    "f2_p": "O custo estimado de um posicionamento fraco, as oportunidades que o teu perfil vai perdendo em silêncio.",
    "f2_mini": "€ em risco",
    "f3_h": "Reescritas do Título e do Sobre",
    "f3_p": "Reescritas prontas a colar, no teu próprio tom, pensadas para a pesquisa e para as pessoas.",
    "f4_h": "3 ganchos para publicações",
    "f4_p": "Três ganchos de abertura escritos no teu tom, cada um pensado para conquistar o clique no \"ver mais\".",
    "f5_h": "Calendário de 30 dias",
    "f5_p": "Um roteiro semana a semana: duas publicações fortes, duas semanas de interação, zero enchimento.",
    "f6_h": "Alvos de networking",
    "f6_p": "Exatamente quem contactar, com mensagens de ligação e de seguimento prontas a colar.",
    "writer_eyebrow": "Depois do relatório",
    "writer_h2": "O relatório é o primeiro dia. Depois, passa a escrever contigo.",
    "writer_p": "Cria uma conta grátis e o plano deixa de ser um documento. O teu tom fica guardado, o teu próximo post é escrito e o teu progresso é medido.",
    "w1_h": "Post Writer",
    "w1_p": "Cola um rascunho ou uma ideia inacabada. Recebes de volta um post pronto para o LinkedIn no teu tom, a começar pelo gancho, assente nas mesmas regras do teu plano. Diz-lhe o que mudar e ele afina o texto.",
    "w2_h": "O teu tom, guardado",
    "w2_p": "O teu relatório já aprendeu como escreves. O Post Writer reutiliza esse tom em cada novo post, para que soe a ti, não a um modelo. Nada para voltar a carregar.",
    "w3_h": "Uma pontuação que podes voltar a medir",
    "w3_p": "Cada relatório fica guardado no teu painel. Aplica as correções, repete a análise e a pontuação acompanha a melhoria, porque mede o teu perfil em vez de adivinhar.",
    "founder_h": "Criado por Ali Azad",
    "founder_role": "10+ ANOS EM SOCIAL · HUAWEI · QIAGEN",
    "founder_p": "O Ali constrói e gere um programa de liderança de pensamento no LinkedIn para executivos, é disso que vive. O seu programa na QIAGEN chegou a 3.5M+ impressões e a sua própria audiência passou os 10k+ seguidores. Transformar perfis em vozes reconhecidas é o seu trabalho diário, por isso cada tática do LinkedScore é primeiro testada em perfis reais de executivos e só depois transformada num plano para o teu.",
    "founder_cta": "Trabalha 1:1 com o Ali",
    "final_h": "Vê como estás posicionado.",
    "final_p": "Cerca de dez minutos. Totalmente grátis. Sem cartão, sem tretas, só as tuas duas pontuações, o teu plano e um Post Writer no teu tom.",
    "footer_tagline": "LinkedScore. Torna-te uma voz, não apenas um número.",
    "footer_privacy": "Privacidade",
    "footer_terms": "Termos",
    "footer_imprint": "Informações legais",
    "footer_cookies": "Cookies",
    "switcher_aria": "Idioma"
  },
  "nl": {
    "nav_how": "Zo werkt het",
    "nav_what": "Wat je krijgt",
    "nav_blog": "Blog",
    "nav_about": "Over ons",
    "nav_cta": "Je score",
    "hero_eyebrow": "LinkedIn Intelligence",
    "hero_h1": "<span class=\"gold\">Kraak het LinkedIn-algoritme.</span> Word gezien.",
    "hero_lede": "LinkedScore leest je profiel, content en positionering, en geeft je daarna een persoonlijk plan met score om precies te fixen wat je bereik kost.",
    "edge1": "Leest je echte <b>posts</b>, niet alleen je profiel",
    "edge2": "<b>Twee scores</b>, voor je profiel en je thought leadership",
    "edge3": "Een plan dat je een <b>stem</b> maakt, niet zomaar een getal",
    "edge4": "Een <b>Post Writer</b> die je volgende posts in jouw stem schrijft",
    "hero_cta": "Ontvang je score, gratis →",
    "hero_cta2": "Bekijk wat erin zit",
    "proof_impressions": "<b>3.5M+ impressies</b> achter de methode",
    "proof_time": "Ongeveer 10 minuten",
    "proof_nocard": "Geen kaart nodig",
    "dash_label": "Jouw LinkedScore",
    "dash_tag": "Kan beter",
    "dash_outof": "VAN 100",
    "dash_note_h": "Voorbeeldscore. De jouwe komt uit je echte profiel.",
    "dash_note_p": "Je kopregel en Info-sectie bepalen de meeste punten, of je ze nu wint of verliest. Het plan laat precies zien wat je moet aanpassen.",
    "bar_headline": "Kopregel",
    "bar_about": "Info-sectie",
    "bar_experience": "Werkervaring",
    "how_eyebrow": "Zo werkt het",
    "how_h2": "In drie stappen naar een stem die wordt herkend.",
    "how_p": "Geen standaardadvies. We lezen je echte profiel en je werkelijke posts, en bouwen het plan rond jou.",
    "step_label": "STAP",
    "step1_h": "Laat je echte werk zien",
    "step1_p": "Voeg je LinkedIn-profiel en screenshots van je laatste 3 posts toe, zodat we lezen wat je echt publiceert, niet alleen je kopregel.",
    "step2_h": "Beantwoord een paar vragen",
    "step2_p": "Vertel ons je doel en je toon in zo'n tien snelle vragen die het hele plan rond jou vormen.",
    "step3_h": "Ontvang twee scores",
    "step3_p": "Je LinkedIn Score en je Thought Leader Score, zodat je precies ziet waar je profiel en je content staan.",
    "get_eyebrow": "Wat je krijgt",
    "get_h2": "De meeste tools stoppen bij een score. Wij niet.",
    "get_p": "Elk onderdeel is afgestemd op jouw rol, jouw doel en wat je profiel nu al laat zien.",
    "f1_h": "Je twee scores",
    "f1_p": "Een LinkedIn Score voor je profiel en een Thought Leader Score voor je posts, elk van 0 tot 100 met een analyse per sectie.",
    "f2_h": "Omzet die je misloopt™",
    "f2_p": "De geschatte kosten van zwakke positionering, de kansen die je profiel stilletjes laat liggen.",
    "f2_mini": "€ op het spel",
    "f3_h": "Herschreven kopregel & Info",
    "f3_p": "Kant-en-klare herschrijvingen in jouw eigen stem, gebouwd voor zoekmachines én voor mensen.",
    "f4_h": "3 post-hooks",
    "f4_p": "Drie openingshooks geschreven in jouw stem, elk ontworpen om die klik op \"meer weergeven\" te verdienen.",
    "f5_h": "Kalender van 30 dagen",
    "f5_p": "Een routekaart week voor week: twee sterke posts, twee weken interactie, nul opvulling.",
    "f6_h": "Netwerkdoelen",
    "f6_p": "Precies wie je moet benaderen, met kant-en-klare connectie- en opvolgberichten.",
    "writer_eyebrow": "Na het rapport",
    "writer_h2": "Het rapport is dag één. Daarna schrijft het met je mee.",
    "writer_p": "Maak een gratis account aan en het plan is niet langer een document. Je stem wordt bewaard, je volgende post wordt alvast geschreven en je voortgang wordt gemeten.",
    "w1_h": "Post Writer",
    "w1_p": "Plak een ruwe opzet of een half uitgewerkt idee. Je krijgt een kant-en-klare LinkedIn-post terug in jouw stem, met de hook voorop, gebouwd op dezelfde regels als je plan. Vertel wat er anders moet en hij past het aan.",
    "w2_h": "Jouw stem, bewaard",
    "w2_p": "Je rapport heeft al geleerd hoe jij schrijft. De Post Writer hergebruikt die stem voor elke nieuwe post, zodat het klinkt als jij, niet als een sjabloon. Je hoeft niets opnieuw te uploaden.",
    "w3_h": "Een score die je opnieuw kunt testen",
    "w3_p": "Elk rapport wordt bewaard in je dashboard. Voer de aanpassingen door, doe de test opnieuw en de score beweegt mee met je verbetering, want hij meet je profiel in plaats van te gokken.",
    "founder_h": "Gemaakt door Ali Azad",
    "founder_role": "10+ JAAR IN SOCIAL · HUAWEI · QIAGEN",
    "founder_p": "Ali bouwt en runt voor de kost een LinkedIn thought-leadership-programma voor executives. Zijn QIAGEN-programma haalde 3.5M+ impressies en zijn eigen volgersaantal groeide naar 10k+. Profielen omzetten in stemmen die worden herkend is zijn dagelijks werk, dus elke tactiek in LinkedScore wordt eerst op echte executive-profielen getest, daarna omgezet in een plan voor het jouwe.",
    "founder_cta": "Werk 1-op-1 met Ali",
    "final_h": "Ontdek hoe je staat gepositioneerd.",
    "final_p": "Ongeveer tien minuten. Helemaal gratis. Geen kaart, geen gezwets, alleen je twee scores, je plan en een Post Writer in jouw stem.",
    "footer_tagline": "LinkedScore. Word een stem, niet zomaar een getal.",
    "footer_privacy": "Privacy",
    "footer_terms": "Voorwaarden",
    "footer_imprint": "Juridische informatie",
    "footer_cookies": "Cookies",
    "switcher_aria": "Taal"
  },
  "it": {
    "nav_how": "Come funziona",
    "nav_what": "Cosa ottieni",
    "nav_blog": "Blog",
    "nav_about": "Chi siamo",
    "nav_cta": "Il tuo score",
    "hero_eyebrow": "Intelligenza per LinkedIn",
    "hero_h1": "<span class=\"gold\">Decifra l'algoritmo di LinkedIn.</span> Fatti notare.",
    "hero_lede": "LinkedScore analizza profilo, contenuti e posizionamento, poi ti consegna un piano personalizzato e con punteggio per sistemare esattamente ciò che ti sta togliendo visibilità.",
    "edge1": "Legge i tuoi <b>post</b> reali, non solo il profilo",
    "edge2": "<b>Due punteggi</b>, per il tuo profilo e per la tua thought leadership",
    "edge3": "Un piano per farti diventare una <b>voce</b>, non solo un numero",
    "edge4": "Un <b>Post Writer</b> che scrive i tuoi prossimi post nel tuo tono",
    "hero_cta": "Calcola il tuo punteggio, gratis →",
    "hero_cta2": "Guarda cosa c'è dentro",
    "proof_impressions": "<b>Oltre 3.5M+ di impression</b> dietro il metodo",
    "proof_time": "Circa 10 minuti",
    "proof_nocard": "Nessuna carta richiesta",
    "dash_label": "Il tuo LinkedScore",
    "dash_tag": "Da migliorare",
    "dash_outof": "SU 100",
    "dash_note_h": "Punteggio di esempio. Il tuo nasce dal tuo profilo reale.",
    "dash_note_p": "È nel titolo e nella sezione Informazioni che si vince o si perde la maggior parte dei punti. Il piano ti mostra le correzioni esatte.",
    "bar_headline": "Titolo",
    "bar_about": "Sezione Informazioni",
    "bar_experience": "Esperienza",
    "how_eyebrow": "Come funziona",
    "how_h2": "Tre passi per diventare una voce riconosciuta.",
    "how_p": "Niente consigli generici. Leggiamo il tuo profilo reale e i tuoi post veri, poi costruiamo il piano su di te.",
    "step_label": "PASSO",
    "step1_h": "Mostra il tuo lavoro reale",
    "step1_p": "Aggiungi il tuo profilo LinkedIn e gli screenshot dei tuoi ultimi 3 post, così leggiamo ciò che pubblichi davvero, non solo il tuo titolo.",
    "step2_h": "Rispondi a qualche domanda",
    "step2_p": "Dicci il tuo obiettivo e il tuo tono in una decina di domande veloci che modellano l'intero piano su di te.",
    "step3_h": "Ricevi due punteggi",
    "step3_p": "Il tuo LinkedIn Score e il tuo Thought Leader Score, così vedi esattamente a che punto sono il tuo profilo e i tuoi contenuti.",
    "get_eyebrow": "Cosa ottieni",
    "get_h2": "Gli altri strumenti si fermano a un punteggio. Noi no.",
    "get_p": "Ogni parte è personalizzata sul tuo ruolo, sul tuo obiettivo e su ciò che il tuo profilo già mostra.",
    "f1_h": "I tuoi due punteggi",
    "f1_p": "Un LinkedIn Score per il tuo profilo e un Thought Leader Score per i tuoi post, ciascuno da 0 a 100 con un'analisi sezione per sezione.",
    "f2_h": "Fatturato a Rischio™",
    "f2_p": "Il costo stimato di un posizionamento debole, le opportunità che il tuo profilo sta perdendo in silenzio.",
    "f2_mini": "€ a rischio",
    "f3_h": "Titolo e Informazioni riscritti",
    "f3_p": "Riscritture pronte da incollare, nel tuo tono, pensate per la ricerca e per le persone.",
    "f4_h": "3 hook per i post",
    "f4_p": "Tre hook di apertura scritti nel tuo tono, ognuno progettato per guadagnare il clic su \"mostra altro\".",
    "f5_h": "Calendario di 30 giorni",
    "f5_p": "Una roadmap settimana per settimana: due post forti, due settimane di engagement, zero riempitivi.",
    "f6_h": "Contatti da coltivare",
    "f6_p": "Esattamente chi contattare, con messaggi di collegamento e follow-up pronti da incollare.",
    "writer_eyebrow": "Dopo il report",
    "writer_h2": "Il report è solo il primo giorno. Poi scrive con te.",
    "writer_p": "Crea un account gratuito e il piano smette di essere un documento. Il tuo tono viene salvato, il tuo prossimo post viene scritto e i tuoi progressi vengono misurati.",
    "w1_h": "Post Writer",
    "w1_p": "Incolla una bozza grezza o una mezza idea. Ricevi un post pronto per LinkedIn nel tuo tono, con l'hook in apertura, costruito sulle stesse regole del tuo piano. Digli cosa cambiare e lo perfeziona.",
    "w2_h": "Il tuo tono, salvato",
    "w2_p": "Il tuo report ha già imparato come scrivi. Il Post Writer riutilizza quel tono per ogni nuovo post, così ognuno suona come te, non come un template. Niente da ricaricare.",
    "w3_h": "Un punteggio che puoi rimisurare",
    "w3_p": "Ogni report viene salvato nella tua dashboard. Applica le correzioni, rifai l'analisi e il punteggio si muove insieme ai tuoi miglioramenti, perché misura il tuo profilo invece di tirare a indovinare.",
    "founder_h": "Creato da Ali Azad",
    "founder_role": "10+ ANNI NEI SOCIAL · HUAWEI · QIAGEN",
    "founder_p": "Ali costruisce e gestisce per lavoro un programma di thought leadership su LinkedIn per dirigenti. Il suo programma in QIAGEN ha raggiunto oltre 3.5M+ di impression e il suo seguito ha superato i 10k+. Trasformare i profili in voci riconosciute è il suo mestiere quotidiano, perciò ogni tattica di LinkedScore viene prima testata su profili executive reali, poi trasformata in un piano per il tuo.",
    "founder_cta": "Lavora 1:1 con Ali",
    "final_h": "Scopri come sei posizionato.",
    "final_p": "Circa dieci minuti. Completamente gratis. Niente carta, niente fronzoli, solo i tuoi due punteggi, il piano e un Post Writer nel tuo tono.",
    "footer_tagline": "LinkedScore. Diventa una voce, non solo un numero.",
    "footer_privacy": "Privacy",
    "footer_terms": "Termini",
    "footer_imprint": "Note legali",
    "footer_cookies": "Cookie",
    "switcher_aria": "Lingua"
  }
};

export const HOME_META = {
  "en": {
    "title": "LinkedScore | LinkedIn Growth Plan",
    "description": "Get your free LinkedIn Score and a personalized AI growth plan: profile rewrites, post hooks, a 30-day roadmap and a Post Writer in your voice."
  },
  "de": {
    "title": "LinkedScore | Dein LinkedIn-Score & KI-Plan",
    "description": "Hol dir deinen kostenlosen LinkedIn-Score und einen persönlichen KI-Wachstumsplan: Profil-Rewrites, Post-Hooks, 30-Tage-Roadmap und ein Post Writer in deinem Ton."
  },
  "fr": {
    "title": "LinkedScore | Votre score et plan LinkedIn par IA",
    "description": "Obtenez votre score LinkedIn gratuit et un plan de croissance par IA : profil réécrit, accroches de posts, feuille de route 30 jours et Post Writer dans votre ton."
  },
  "es": {
    "title": "LinkedScore | Plan de crecimiento en LinkedIn",
    "description": "Consigue gratis tu puntuación de LinkedIn y un plan de crecimiento con IA: mejoras de perfil, ganchos para posts, hoja de ruta de 30 días y Post Writer en tu voz."
  },
  "pt": {
    "title": "LinkedScore | Plano de Crescimento no LinkedIn",
    "description": "Descobre a tua pontuação do LinkedIn grátis e um plano de crescimento com IA: reescritas do perfil, ganchos, roteiro de 30 dias e um Post Writer no teu tom."
  },
  "nl": {
    "title": "LinkedScore | Jouw LinkedIn-groeiplan met AI",
    "description": "Ontvang gratis je LinkedIn-score en een persoonlijk AI-groeiplan: herschreven profiel, post-hooks, een routekaart van 30 dagen en een Post Writer in jouw stem."
  },
  "it": {
    "title": "LinkedScore | Piano di crescita su LinkedIn con IA",
    "description": "Scopri il tuo punteggio LinkedIn gratis e un piano di crescita con IA: profilo riscritto, hook per i post, roadmap di 30 giorni e un Post Writer nel tuo tono."
  }
};
